/* Integration QA against generated original output, never edits the app. */
const { chromium } = require(process.env.NETWORK_PLAYWRIGHT || 'C:/Users/kcg51/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs'), path=require('path'), assert=require('assert');
(async()=>{
const base=process.argv[2]||'http://127.0.0.1:8876';
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});
const errors=[];
try{
for(const [width,scheme] of [[1440,'light'],[1024,'dark'],[740,'light'],[360,'dark']]){
const page=await browser.newPage({viewport:{width,height:1000},colorScheme:scheme});
page.on('pageerror',e=>errors.push(e.message));
await page.goto(base+'/causal-network.html',{waitUntil:'load'});
await page.locator('#graph canvas').first().waitFor();
assert.strictEqual(await page.locator('#node-count').innerText(),'12');
assert.strictEqual(await page.locator('#edge-count').innerText(),'14');
const initial=await page.evaluate(()=>globalThis.__macroCanvasDiagnostics());
assert.strictEqual(initial.selected,'usdkrw');
assert(initial.upstream.includes('fed-rate'));
assert(initial.downstream.includes('kospi'));
assert(initial.downstream.includes('housing'));
assert(initial.positiveEdges>0&&initial.negativeEdges>0&&initial.dimmed>0);
assert.deepStrictEqual(initial.detail,{unit:'KRW/USD',asOf:'2026-09-04',cadence:'일간',region:'한국'});
assert.match(await page.locator('#inspector-content').innerText(),/가상 현재 값/);
assert.match(await page.locator('#inspector-content').innerText(),/이 값이 뜻하는 것/);
if(width<=1024)assert.strictEqual(await page.locator('#toggle-inspector').getAttribute('aria-expanded'),'false');
await page.evaluate(()=>globalThis.__macroCanvasSelect('inflation'));
await page.locator('#selected-title').getByText('소비자물가 압력',{exact:true}).waitFor();
const focused=await page.evaluate(()=>globalThis.__macroCanvasDiagnostics());
assert(focused.upstream.includes('oil-price')&&focused.upstream.includes('fed-rate'));
assert(focused.downstream.includes('bond-yield')&&focused.downstream.includes('housing'));
assert.strictEqual(focused.detail.cadence,'월간');
assert.match(await page.locator('.snapshot-card').innerText(),/2026-08/);
assert.match(await page.locator('.snapshot-card').innerText(),/\+3\.1%/);
const beforeRelationPan=focused.pan;
await page.locator('.relation-item[data-node="bond-yield"]').click();
await page.locator('#selected-title').getByText('한국 10년 금리',{exact:true}).waitFor();
await page.waitForTimeout(260);
const relationMoved=await page.evaluate(()=>globalThis.__macroCanvasDiagnostics());
assert.strictEqual(relationMoved.selected,'bond-yield');
assert.notDeepStrictEqual(relationMoved.pan,beforeRelationPan);
assert.match(await page.evaluate(()=>location.search),/node=bond-yield/);
await page.evaluate(()=>globalThis.__macroCanvasSelect('inflation'));
await page.locator('#selected-title').getByText('소비자물가 압력',{exact:true}).waitFor();
const tooltip=await page.evaluate(()=>globalThis.__macroCanvasHoverEdge('e-cpi-consumer'));
assert.match(tooltip,/소비자물가 압력 → 소비 심리/);assert.match(tooltip,/NEGATIVE RELATION/);
assert(await page.locator('#graph-tooltip').isVisible());
await page.evaluate(()=>document.getElementById('graph-tooltip').hidden=true);
if(width<=1024){fs.mkdirSync('artifacts/causal-network',{recursive:true});await page.screenshot({path:`artifacts/causal-network/node-detail-open-${width}-${scheme}.png`,fullPage:false});await page.locator('#close-inspector').focus();await page.keyboard.press('Shift+Tab');assert(await page.locator('.relation-item').last().evaluate(el=>document.activeElement===el));await page.keyboard.press('Tab');assert(await page.locator('#close-inspector').evaluate(el=>document.activeElement===el));await page.keyboard.press('Escape');assert.strictEqual(await page.locator('#toggle-inspector').getAttribute('aria-expanded'),'false');assert(await page.locator('#toggle-inspector').evaluate(el=>document.activeElement===el));}
assert.strictEqual(await page.evaluate(()=>globalThis.__macroCanvasTapEdge('e-fx-flow')),true);
await page.locator('#selected-title').getByText('원/달러 환율 → 외국인 주식 수급',{exact:true}).waitFor();
const edgeFocused=await page.evaluate(()=>globalThis.__macroCanvasDiagnostics());
assert.strictEqual(edgeFocused.selectionMode,'edge');assert.strictEqual(edgeFocused.selected,null);assert.strictEqual(edgeFocused.selectedEdge,'e-fx-flow');
assert.deepStrictEqual(edgeFocused.edgeEndpoints.sort(),['foreign-flow','usdkrw']);assert.deepStrictEqual(edgeFocused.highlightedEdges,['e-fx-flow']);assert.strictEqual(edgeFocused.dimmed,23);
assert.strictEqual(edgeFocused.detail.sign,'-');assert.match(edgeFocused.detail.mechanism,/달러 기준 수익률/);assert.match(edgeFocused.detail.condition,/환노출/);assert.match(edgeFocused.detail.counterforce,/지수 리밸런싱/);assert.strictEqual(edgeFocused.detail.lag,'가상 당일–4주');
const edgePanelText=await page.locator('#inspector-content').innerText();assert.match(edgePanelText,/부정 관계/);assert.match(edgePanelText,/전달 메커니즘/);assert.match(edgePanelText,/성립 조건/);assert.match(edgePanelText,/완충·반대 요인/);assert.match(edgePanelText,/가상 전달 시차/);
const edgeSearch=await page.evaluate(()=>location.search);assert.match(edgeSearch,/edge=e-fx-flow/);assert.doesNotMatch(edgeSearch,/node=/);
if(width<=1024){assert.strictEqual(await page.locator('#toggle-inspector').getAttribute('aria-expanded'),'true');fs.mkdirSync('artifacts/causal-network',{recursive:true});await page.screenshot({path:`artifacts/causal-network/edge-detail-open-${width}-${scheme}.png`,fullPage:false});await page.locator('#close-inspector').focus();await page.keyboard.press('Shift+Tab');assert(await page.locator('[data-endpoint="target"]').evaluate(el=>document.activeElement===el));await page.keyboard.press('Tab');assert(await page.locator('#close-inspector').evaluate(el=>document.activeElement===el));}
await page.locator('[data-endpoint="source"]').click();
await page.locator('#selected-title').getByText('원/달러 환율',{exact:true}).waitFor();
const sourceMoved=await page.evaluate(()=>globalThis.__macroCanvasDiagnostics());assert.strictEqual(sourceMoved.selectionMode,'node');assert.strictEqual(sourceMoved.selected,'usdkrw');assert.strictEqual(sourceMoved.selectedEdge,null);assert.match(await page.evaluate(()=>location.search),/node=usdkrw/);assert.doesNotMatch(await page.evaluate(()=>location.search),/edge=/);
if(width<=1024){await page.keyboard.press('Escape');assert.strictEqual(await page.locator('#toggle-inspector').getAttribute('aria-expanded'),'false');}
await page.goto(base+'/causal-network.html?edge=e-fx-flow',{waitUntil:'load'});await page.locator('#graph canvas').first().waitFor();
const restoredEdge=await page.evaluate(()=>globalThis.__macroCanvasDiagnostics());assert.strictEqual(restoredEdge.selectionMode,'edge');assert.strictEqual(restoredEdge.selectedEdge,'e-fx-flow');assert.deepStrictEqual(restoredEdge.highlightedEdges,['e-fx-flow']);
if(width<=1024)assert.strictEqual(await page.locator('#toggle-inspector').getAttribute('aria-expanded'),'false');
if(width<=1024){await page.click('#toggle-drivers');assert.strictEqual(await page.locator('#toggle-drivers').getAttribute('aria-expanded'),'true');}
await page.locator('#path-from').selectOption('oil-price');await page.locator('#path-to').selectOption('housing');await page.click('#find-path');
await page.locator('#selected-title').getByText('국제유가 → 주택 수요',{exact:true}).waitFor();
const pathFocused=await page.evaluate(()=>globalThis.__macroCanvasDiagnostics());assert.strictEqual(pathFocused.selectionMode,'path');assert.strictEqual(pathFocused.selected,null);assert.strictEqual(pathFocused.selectedEdge,null);
assert.deepStrictEqual(pathFocused.path.nodes,['oil-price','inflation','bond-yield','housing']);assert.deepStrictEqual(pathFocused.path.edges,['e-oil-cpi','e-cpi-yield','e-yield-housing']);assert.strictEqual(pathFocused.path.stepIndex,0);assert.strictEqual(pathFocused.path.error,false);assert.strictEqual(pathFocused.dimmed,19);assert.deepStrictEqual(pathFocused.activePathEdge,['e-oil-cpi']);
const pathText=await page.locator('#inspector-content').innerText();assert.match(pathText,/가장 짧은 경로/);assert.match(pathText,/국제유가 → 소비자물가 압력/);assert.match(pathText,/소비자물가 압력 → 한국 10년 금리/);assert.match(pathText,/한국 10년 금리 → 주택 수요/);assert.strictEqual(await page.locator('#path-prev').isDisabled(),true);assert.strictEqual(await page.locator('#path-next').isDisabled(),false);
const pathSearch=await page.evaluate(()=>location.search);assert.match(pathSearch,/from=oil-price/);assert.match(pathSearch,/to=housing/);assert.doesNotMatch(pathSearch,/node=|edge=/);
if(width<=1024){assert.strictEqual(await page.locator('#toggle-drivers').getAttribute('aria-expanded'),'false');assert.strictEqual(await page.locator('#toggle-inspector').getAttribute('aria-expanded'),'true');}
await page.click('#path-next');await page.waitForTimeout(260);let pathStep=await page.evaluate(()=>globalThis.__macroCanvasDiagnostics());assert.strictEqual(pathStep.path.stepIndex,1);assert.deepStrictEqual(pathStep.activePathEdge,['e-cpi-yield']);assert.strictEqual(await page.locator('.path-step-card').nth(1).getAttribute('aria-current'),'step');
await page.click('#path-next');await page.waitForTimeout(260);pathStep=await page.evaluate(()=>globalThis.__macroCanvasDiagnostics());assert.strictEqual(pathStep.path.stepIndex,2);assert.deepStrictEqual(pathStep.activePathEdge,['e-yield-housing']);assert.strictEqual(await page.locator('#path-next').isDisabled(),true);
await page.click('#path-prev');await page.waitForTimeout(260);assert.strictEqual((await page.evaluate(()=>globalThis.__macroCanvasDiagnostics())).path.stepIndex,1);
const fitCount=(await page.evaluate(()=>globalThis.__macroCanvasDiagnostics())).pathFitCount;await page.click('#path-fit');await page.waitForTimeout(260);assert.strictEqual((await page.evaluate(()=>globalThis.__macroCanvasDiagnostics())).pathFitCount,fitCount+1);
if(width<=1024){fs.mkdirSync('artifacts/causal-network',{recursive:true});await page.screenshot({path:`artifacts/causal-network/path-explorer-open-${width}-${scheme}.png`,fullPage:false});await page.locator('#close-inspector').focus();await page.keyboard.press('Shift+Tab');assert(await page.locator('.path-step-card').last().evaluate(el=>document.activeElement===el));await page.keyboard.press('Tab');assert(await page.locator('#close-inspector').evaluate(el=>document.activeElement===el));await page.keyboard.press('Escape');assert.strictEqual(await page.locator('#toggle-inspector').getAttribute('aria-expanded'),'false');}
await page.goto(base+'/causal-network.html?from=oil-price&to=housing',{waitUntil:'load'});await page.locator('#graph canvas').first().waitFor();const restoredPath=await page.evaluate(()=>globalThis.__macroCanvasDiagnostics());assert.strictEqual(restoredPath.selectionMode,'path');assert.deepStrictEqual(restoredPath.path.edges,['e-oil-cpi','e-cpi-yield','e-yield-housing']);assert.deepStrictEqual(restoredPath.activePathEdge,['e-oil-cpi']);if(width<=1024)assert.strictEqual(await page.locator('#toggle-inspector').getAttribute('aria-expanded'),'false');
const beforeZoom=(await page.evaluate(()=>globalThis.__macroCanvasDiagnostics())).zoom;
await page.click('#zoom-in');await page.waitForTimeout(220);
assert((await page.evaluate(()=>globalThis.__macroCanvasDiagnostics())).zoom>beforeZoom);
await page.evaluate(()=>document.getElementById('fit').click());
await page.evaluate(()=>document.getElementById('clear-selection').click());
assert.strictEqual((await page.evaluate(()=>globalThis.__macroCanvasDiagnostics())).dimmed,0);
await page.evaluate(()=>globalThis.__macroCanvasSelect('usdkrw'));
if(width<=1024){assert.strictEqual(await page.locator('#toggle-inspector').getAttribute('aria-expanded'),'true');await page.click('#close-inspector');await page.click('#toggle-drivers');assert.strictEqual(await page.locator('#toggle-drivers').getAttribute('aria-expanded'),'true');await page.press('body','Escape');await page.waitForTimeout(260);}
assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
fs.mkdirSync('artifacts/causal-network',{recursive:true});await page.screenshot({path:`artifacts/causal-network/canvas-mvp-${width}-${scheme}.png`,fullPage:false});
console.log(JSON.stringify({width,scheme,nodes:12,edges:14,nodeFocus:true,edgeDetail:true,pathExplorer:true,pathSteps:true,pathUrlRestore:true,mobileTap:true,tooltip:true,zoom:true,overflow:false}));
await page.close();
}
const page=await browser.newPage();await page.goto(base+'/index.html#search?q='+encodeURIComponent('시계열'),{waitUntil:'load'});
await page.locator('#searchMacro a[href="causal-network.html"]').waitFor();
await page.goto(base+'/macro.html',{waitUntil:'load'});await page.locator('a[href="causal-network.html"]').waitFor();
await page.goto(base+'/index.html#search?q='+encodeURIComponent('엔캐리'),{waitUntil:'load'});
await page.locator('#searchMacro a[href="macro.html?scenario=yen-carry"]').waitFor();
await page.goto(base+'/macro.html?scenario=yen-carry&node=carry-risk-adjusted-return',{waitUntil:'load'});
await page.locator('[data-scenario-panel="yen-carry"]:visible').waitFor();
await page.locator('#cid-detail-title').getByText('엔 캐리의 위험조정 매력',{exact:true}).waitFor();
assert.strictEqual(await page.locator('.scenario-picker [data-scenario="yen-carry"]').getAttribute('aria-pressed'),'true');
assert((await page.locator('.scenario-picker button').count())>=8);
assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.screenshot({path:'artifacts/causal-network/yen-carry-detail.png',fullPage:false});
await page.goto(base+'/index.html#search?q='+encodeURIComponent('환산수익률'),{waitUntil:'load'});
await page.locator('#searchMacro a[href="macro.html?scenario=yen-carry"]').waitFor();
await page.goto(base+'/macro.html?scenario=yen-carry&node=currency-adjusted-equity-return',{waitUntil:'load'});
await page.locator('[data-scenario-panel="yen-carry"]:visible').waitFor();
await page.locator('#cid-detail-title').getByText('기준통화 환산 주식수익률',{exact:true}).waitFor();
assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.screenshot({path:'artifacts/causal-network/currency-adjusted-return-detail.png',fullPage:false});
await page.goto(base+'/index.html#search?q='+encodeURIComponent('채권가격'),{waitUntil:'load'});
await page.locator('#searchMacro a[href="macro.html?scenario=rates"]').waitFor();
await page.goto(base+'/macro.html?scenario=rates&node=fixed-rate-bond-price',{waitUntil:'load'});
await page.locator('[data-scenario-panel="rates"]:visible').waitFor();
await page.locator('#cid-detail-title').getByText('기존 고정금리 장기채 가격',{exact:true}).waitFor();
assert.strictEqual(await page.locator('.scenario-picker [data-scenario="rates"]').getAttribute('aria-pressed'),'true');
assert.strictEqual(await page.evaluate(()=>getComputedStyle(document.querySelector('.cid-rates-asset-lanes')).gridTemplateColumns.split(' ').length),2);
assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.screenshot({path:'artifacts/causal-network/fixed-rate-bond-detail.png',fullPage:false});
await page.goto(base+'/index.html#search?q='+encodeURIComponent('국채선물 증거금'),{waitUntil:'load'});
await page.locator('#searchMacro a[href="macro.html?scenario=rates"]').waitFor();
await page.goto(base+'/macro.html?scenario=rates&node=ktb-futures-margin-call',{waitUntil:'load'});
await page.locator('[data-scenario-panel="rates"]:visible').waitFor();
await page.locator('#cid-detail-title').getByText('추가증거금·포지션 축소 압력',{exact:true}).waitFor();
assert.strictEqual(await page.locator('.cid-rates-derivatives-lane').count(),1);
assert.strictEqual(await page.locator('.cid-rates-derivatives-lane').evaluate(el=>getComputedStyle(el).gridColumnEnd),'-1');
assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.locator('.cid-rates-derivatives-lane').screenshot({path:'artifacts/causal-network/ktb-futures-margin-call.png'});
await page.goto(base+'/index.html#search?q='+encodeURIComponent('러셀2000'),{waitUntil:'load'});
await page.locator('#searchMacro a[href="macro.html?scenario=rates"]').waitFor();
await page.goto(base+'/macro.html?scenario=rates&node=russell2000-relative-downside-pressure',{waitUntil:'load'});
await page.locator('[data-scenario-panel="rates"]:visible').waitFor();
await page.locator('#cid-detail-title').getByText('Russell 2000 상대성과 하방 압력',{exact:true}).waitFor();
assert.match(await page.locator('#cid-limits').innerText(),/보장 수익/);
assert.match(await page.locator('#cid-limits').innerText(),/자동 소멸/);
assert.strictEqual(await page.locator('.cid-rates-smallcap-lane').count(),1);
assert.strictEqual(await page.locator('.cid-rates-smallcap-lane').evaluate(el=>getComputedStyle(el).gridColumnEnd),'-1');
assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.locator('.cid-rates-smallcap-lane').screenshot({path:'artifacts/causal-network/russell2000-smallcap-path.png'});
await page.goto(base+'/index.html#search?q='+encodeURIComponent('PF ABCP'),{waitUntil:'load'});
await page.locator('#searchMacro a[href="macro.html?scenario=korea-pf-liquidity"]').waitFor();
await page.goto(base+'/macro.html?scenario=korea-pf-liquidity&node=kr-pf-abcp-rollover-risk',{waitUntil:'load'});
await page.locator('[data-scenario-panel="korea-pf-liquidity"]:visible').waitFor();
await page.locator('#cid-detail-title').getByText('PF-ABCP·ABSTB 차환·가격 경색',{exact:true}).waitFor();
assert.strictEqual(await page.locator('.scenario-picker [data-scenario="korea-pf-liquidity"]').getAttribute('aria-pressed'),'true');
assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.screenshot({path:'artifacts/causal-network/korea-pf-detail.png',fullPage:false});
await page.goto(base+'/index.html#search?q='+encodeURIComponent('유럽 천연가스'),{waitUntil:'load'});
await page.locator('#searchMacro a[href="macro.html?scenario=middle-east-wage-price"]').waitFor();
await page.goto(base+'/macro.html?scenario=middle-east-wage-price&node=europe-gas-price',{waitUntil:'load'});
await page.locator('[data-scenario-panel="middle-east-wage-price"]:visible').waitFor();
await page.locator('#cid-detail-title').getByText('유럽 천연가스 가격(TTF)',{exact:true}).waitFor();
assert.strictEqual(await page.locator('.scenario-picker [data-scenario="middle-east-wage-price"]').getAttribute('aria-pressed'),'true');
assert.strictEqual(await page.locator('[data-scenario-panel="middle-east-wage-price"] .cid-rate-lane').count(),2);
assert.match(await page.locator('[data-scenario-panel="middle-east-wage-price"]').innerText(),/세계 AI 산업의 붕괴로 일반화할 수 없음/);
assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.screenshot({path:'artifacts/causal-network/europe-gas-ai-detail.png',fullPage:false});
await page.goto(base+'/index.html#search?q='+encodeURIComponent('자사주'),{waitUntil:'load'});
await page.locator('#searchMacro a[href="macro.html?scenario=buyback-index-flow"]').waitFor();
await page.goto(base+'/macro.html?scenario=buyback-index-flow&node=buyback-program-completion',{waitUntil:'load'});
await page.locator('[data-scenario-panel="buyback-index-flow"]:visible').waitFor();
await page.locator('#cid-detail-title').getByText('자사주 매입 완료·반복 매수 수요 종료',{exact:true}).waitFor();
assert.strictEqual(await page.locator('.scenario-picker [data-scenario="buyback-index-flow"]').getAttribute('aria-pressed'),'true');
assert.match(await page.locator('#cid-limits').innerText(),/11월 19일/);
assert.match(await page.locator('#cid-limits').innerText(),/급락/);
assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.screenshot({path:'artifacts/causal-network/buyback-completion-detail.png',fullPage:false});
for(const [width,scheme,columns] of [[1440,'light',2],[740,'light',2],[360,'dark',1]]){
await page.setViewportSize({width,height:1100});await page.emulateMedia({colorScheme:scheme});
await page.goto(base+'/macro.html?scenario=middle-east-wage-price&node=europe-gas-price',{waitUntil:'load'});
await page.locator('[data-scenario-panel="middle-east-wage-price"]:visible').waitFor();
assert.strictEqual(await page.locator('[data-scenario-panel="middle-east-wage-price"] .cid-rate-lanes').evaluate(el=>getComputedStyle(el).gridTemplateColumns.split(' ').length),columns);
assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.screenshot({path:`artifacts/causal-network/europe-gas-ai-${width}-${scheme}.png`,fullPage:false});
await page.goto(base+'/macro.html?scenario=buyback-index-flow&node=buyback-flow-intensity',{waitUntil:'load'});
await page.locator('[data-scenario-panel="buyback-index-flow"]:visible').waitFor();
assert.strictEqual(await page.locator('[data-scenario-panel="buyback-index-flow"] .cid-rate-lanes').evaluate(el=>getComputedStyle(el).gridTemplateColumns.split(' ').length),columns);
assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.screenshot({path:`artifacts/causal-network/buyback-${width}-${scheme}.png`,fullPage:false});
await page.goto(base+'/macro.html?scenario=rates&node=russell2000-relative-downside-pressure',{waitUntil:'load'});
await page.locator('[data-scenario-panel="rates"]:visible').waitFor();
assert.strictEqual(await page.locator('[data-scenario-panel="rates"] .cid-rates-asset-lanes').evaluate(el=>getComputedStyle(el).gridTemplateColumns.split(' ').length),columns);
assert.strictEqual(await page.locator('.cid-rates-smallcap-lane').evaluate(el=>getComputedStyle(el).gridColumnEnd),width>680?'-1':'auto');
assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.screenshot({path:`artifacts/causal-network/russell2000-${width}-${scheme}.png`,fullPage:false});
}
assert.deepStrictEqual(errors,[]);console.log('Search, buyback/Russell 2000/yen-carry/currency-adjusted return/fixed-rate bond/KTB futures/PF details, return navigation, JS errors: PASS');
}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1);});
